const books = [
  {
    id: 1,
    author: 'Jordan Peterson',
    title: '12 Rules for Life: An Antidote to Chaos',
    slug: '12-rules-for-life:-an-antidote-to-chaos',
    genre: ['Self-Help'],
    available: false,
    borrowedBy: [3],
    img: 'https://images-na.ssl-images-amazon.com/images/I/41kspFBwVxL._SX331_BO1,204,203,200_.jpg',
  },
  {
    id: 2,
    author: 'Blake Crouch',
    title: 'Dark Matter',
    slug: 'dark-matter',
    genre: ['Sci-Fi', 'Thriller'],
    available: false,
    borrowedBy: [3],
    img: 'https://images-na.ssl-images-amazon.com/images/I/81-oJMnQL3L.jpg',
  },
  {
    id: 3,
    author: 'Robin Sloan',
    title: "Mr. Penumbra's 24-Hour Bookstore",
    slug: "mr.-penumbra's-24-hour-bookstore",
    genre: ['Suspense', 'Fantasy'],
    available: false,
    borrowedBy: [1, 3, 5, 1],
    img: 'https://images-na.ssl-images-amazon.com/images/I/71UhnbUOwzL.jpg',
  },
  {
    id: 4,
    author: 'Paul Kalanithi',
    title: 'When Breath Becomes Air',
    slug: 'when-breath-becomes-air',
    genre: ['Biography'],
    available: true,
    borrowedBy: [2, 5],
    img: 'https://images-na.ssl-images-amazon.com/images/I/91iZ2ZQduBL.jpg',
  },
  {
    id: 5,
    author: 'Eric Ries',
    title: 'The Lean Startup',
    slug: 'the-lean-startup',
    genre: ['Business', 'Entrepreneurship'],
    available: false,
    borrowedBy: [4, 2],
    img: 'https://images-na.ssl-images-amazon.com/images/I/81-QB7nDh4L.jpg',
  },
  {
    id: 6,
    author: 'George R.R. Martin',
    title: 'A Storm of Swords',
    slug: 'a-storm-of-swords',
    genre: ['Fantasy'],
    available: true,
    borrowedBy: [],
    img: 'https://images-na.ssl-images-amazon.com/images/I/81AYwaAvX1L.jpg',
  },
  {
    id: 7,
    author: 'Leigh Bardugo',
    title: 'Six of Crows',
    slug: 'six-of-crows',
    genre: ['Fantasy'],
    available: false,
    borrowedBy: [4, 3, 2, 1, 5],
    img: 'https://m.media-amazon.com/images/I/51X-uVznafL.jpg',
  },
  {
    id: 8,
    author: 'Agatha Christie',
    title: "Curtain: Poirot's Last Case",
    slug: "curtain:-poirot's-last-case",
    genre: ['Crime', 'Mystery'],
    available: false,
    borrowedBy: [3, 5],
    img: 'https://images-na.ssl-images-amazon.com/images/I/813H-43Z8-L.jpg',
  },
  {
    id: 9,
    author: 'Elif Shafak',
    title: 'The Forty Rules of Love',
    slug: 'the-forty-rules-of-love',
    genre: ['Fiction'],
    available: false,
    borrowedBy: [5, 1],
    img: 'https://alfagrbookstore.com/image/catalog/products/93/New%20Doc%202021-03-09%2012.15.24_11.jpg',
  },
  {
    id: 10,
    author: 'Leigh Bardugo',
    title: 'The Language of Thorns: Midnight Tales and Dangerous Magic',
    slug: 'the-language-of-thorns:-midnight-tales-and-dangerous-magic',
    genre: ['Fantasy'],
    available: false,
    borrowedBy: [5],
    img: 'https://images-na.ssl-images-amazon.com/images/I/51Jy6-ypOrL._SX334_BO1,204,203,200_.jpg',
  },
];

export default books;
